services:
  webistzupdf:
    # simple mode - webistzupdf/webistzupdf-simple:latest
    # default mode - webistzupdf/webistzupdf:latest
    image: ghcr.io/zara-datacenter/webistzupdf-simple:latest
    container_name: webistzupdf
    restart: unless-stopped
    ports:
      - '8080:8080'
    # For IPv4-only environments
    #environment:
    #  - DISABLE_IPV6=true
